<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CenterDevice.Test</RootNamespace>
    <TargetFrameworks>netcoreapp3.1;net8.0;net48</TargetFrameworks>
    <Authors>Jochen Wezel</Authors>
    <Company>CompuMaster GmbH</Company>
    <Copyright>2019-2026 CompuMaster GmbH</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <OutputType>Library</OutputType>
    <StartupObject />
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="log4net.config" />
    <None Remove="TestFile.txt" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="TestFile.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="JUnitTestLogger4GitHub" Version="1.1.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Scopevisio.Teamwork\CompuMaster.Scopevisio.Teamwork.MiniClone.csproj" />
  </ItemGroup>

</Project>
